version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: taskmind-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskmind
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - taskmind-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: taskmind-backend
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/taskmind
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=7d
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - taskmind-network
    command: npm run dev

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmind-frontend
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - taskmind-network
    command: npm run dev

networks:
  taskmind-network:
    driver: bridge

volumes:
  postgres-data: 